# Use node_modules; it keeps Vite and other tooling simplest.
nodeLinker: node-modules

# This is a public repository, so the lockfile must only reference the public registry.
# Override in a user level ~/.yarnrc.yml to use a mirror.
npmRegistryServer: "https://registry.npmjs.org"
