//
//  Copyright (c) 2026 Viva Republica, Inc.
//

import { createTranslator } from "@necto/bridge";

export const t = createTranslator({
  ko: {
    Control: "Control",
    Gestures: "제스처",
    Tap: "탭",
    Position: "위치",
    "Default position": "기본 위치",
    "Custom position": "직접 지정",
    "X (left to right)": "X (왼쪽 → 오른쪽)",
    "Y (top to bottom)": "Y (위 → 아래)",
    "Use 0–1 within the visible target. Swipe starts here and stops at its edge.": "보이는 요소 안의 위치를 0~1로 입력하세요. 스와이프는 이 위치에서 시작하며 요소 경계를 넘지 않습니다.",
    "Use position.x and position.y between 0 and 1": "X와 Y를 0~1 사이로 입력해 주세요.",
    "There is no room to swipe in that direction": "해당 방향으로 스와이프할 공간이 없습니다.",
    "There is not enough room for these fingers at this position": "이 위치에는 지정한 손가락 수만큼 터치할 공간이 없습니다.",
    Fingers: "손가락 수",
    "Tap count": "탭 횟수",
    "Use 1–5 fingers and 1–3 taps": "손가락 수는 1~5개, 탭 횟수는 1~3회로 입력해 주세요.",
    "Swipe back": "스와이프로 뒤로 가기",
    "Text to enter": "입력할 텍스트",
    "Input mode": "입력 방식",
    "Replace text": "전체 바꾸기",
    "Append text": "끝에 추가",
    "Enter text": "입력",
    "↑ Swipe up": "↑ 위로 스와이프",
    "↓ Swipe down": "↓ 아래로 스와이프",
    "← Swipe left": "← 왼쪽으로 스와이프",
    "→ Swipe right": "→ 오른쪽으로 스와이프",
    "Arrows show finger movement. Swipe up to reveal content below.": "화살표는 손가락을 움직이는 방향입니다. 위로 밀면 아래쪽 내용이 보입니다.",
    "Distance ratio": "이동 거리 비율",
    "Duration (ms)": "동작 시간 (ms)",
    "Sending input…": "입력 전달 중…",
    "Input sent · accessibility content changed": "입력 전달됨 · 접근성 내용이 바뀌었습니다",
    "Input sent · no accessibility change observed": "입력 전달됨 · 접근성 내용의 변화는 확인되지 않았습니다",
    "Another action is in progress": "다른 동작이 실행 중입니다.",
    "The target changed. Refresh Control before acting.": "요소가 바뀌었습니다. 새로고침한 뒤 다시 선택해 주세요.",
    "The target is covered by another view. Refresh Control before acting.": "다른 화면이 요소를 가리고 있습니다. 새로고침한 뒤 다시 선택해 주세요.",
    "The text field did not receive focus. Refresh Control before acting.": "입력란에 포커스가 이동하지 않았습니다. 새로고침한 뒤 다시 선택해 주세요.",
    Actions: "조작",
    "Read accessibility": "접근성 읽기",
    Read: "조회",
    "Filter accessibility content": "접근성 내용 검색",
    "No accessibility content": "읽을 수 있는 접근성 정보가 없습니다",
    "Read the current screen to check text and values.": "현재 화면을 조회해 텍스트와 값을 확인하세요.",
    Role: "역할",
    Label: "레이블",
    Value: "값",
    Heading: "제목",
    Text: "텍스트",
    Link: "링크",
    Image: "이미지",
    Adjustable: "값 조절",
    Element: "요소",
    "Loading…": "조회 중…",
    "Filter elements": "요소 검색",
    "No actionable elements": "조작할 수 있는 요소가 없습니다",
    "Refresh to find controls on the current screen.": "새로고침해 현재 화면의 요소를 확인하세요.",
    Elements: "요소",
    Button: "버튼",
    "Scroll area": "스크롤 영역",
    Screen: "화면",
    Refresh: "새로고침",
    "Nothing matches": "일치하는 요소가 없습니다",
    "Resize the detail pane": "상세 패널 크기 조절",
    "Close details": "상세 닫기",
    "Text input": "텍스트 입력",
    "Secure value is hidden": "비밀번호 값은 표시하지 않습니다",
    "The element moved. Refresh Control before acting.": "요소 위치가 바뀌었습니다. 새로고침한 뒤 다시 선택해 주세요.",
    "This plugin only works inside Necto": "이 플러그인은 Necto 안에서만 동작합니다.",
  },
});
